#!/bin/bash
# netbird-monitor-1.0/DEBIAN/prerm

set -e

case "$1" in
    remove|upgrade|deconfigure)
        # Timer stoppen und deaktivieren
        systemctl stop netbird-monitor.timer || true
        systemctl disable netbird-monitor.timer || true

        # Systemd neu laden
        systemctl daemon-reload || true
        ;;
esac

exit 0
